### ISSUE TITLE
Plugin was not found in any of the following resources

### ISSUE THREAD

**Issue by ramanamuttana** [mvysny/vaadin-boot-example-gradle#1]
* What went wrong:
Plugin [id: 'com.vaadin', version: '23.2.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.vaadin:com.vaadin.gradle.plugin:23.2.0')
  Searched in the following repositories:
   Gradle Central Plugin Repository

I run the code , but i am getting the error as above

**Comment by mvysny** [comment]
Hmm that's strange: the gradle plugins page shows that the gradle plugin 23.2.0 is available at https://plugins.gradle.org/plugin/com.vaadin ... Could you please try to delete your gradle cache and try again?

**Comment by ramanamuttana** [comment]
I tried your suggestion but  it did not work , then i changed the  build.gradle which is shown below , now it works. 
1) now i am able to download the dependencies .



```
plugins {
    id "java"
    id "application"
    id "com.vaadin" version "23.2.0"
}

defaultTasks("clean", "build")

// don't use Jetty 11+ - uses jakarta.Servlet instead of javax.Servlet which makes it incompatible with Vaadin
def jettyVersion = "10.0.11"

repositories {
    mavenCentral()
    maven {
      url "https://plugins.gradle.org/m2/"
      url "https://maven.vaadin.com/vaadin-addons"
    }
}

dependencies {
    // Vaadin
    implementation("com.vaadin:vaadin-core:23.2.0")
    
    implementation("com.vaadin:vaadin-gradle-plugin:23.2.0")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

test {
    useJUnitPlatform()
    testLogging {
        exceptionFormat = "FULL"
    }
}

application {
    mainClassName = "com.vaadin.starter.skeleton.Main"
}

```
